export const SET_FAVORITE_FILTER = "SET_FAVORITE_FILTER";
export const SET_CARDS_VIEW = "SET_CARDS_VIEW";
export const SET_DARK_MODE = "SET_DARK_MODE";
export const SETUP_USER_OPTIONS = "SETUP_USER_OPTIONS";
